import { parseGrid } from '../src/game/board';

/** A real easy-tier puzzle generated by sudoku-gen, frozen for determinism. */
export const FIXTURE_PUZZLE =
  '92-3-6--8---719--61--------4-----9-2-6--95--387--3-6-5--895723---54---69-9216-5-7';
export const FIXTURE_SOLUTION =
  '927346158584719326136582794453671982261895473879234615648957231715423869392168547';

export const fixtureGivens = () => parseGrid(FIXTURE_PUZZLE);
export const fixtureSolution = () => parseGrid(FIXTURE_SOLUTION);
